### PR TITLE
Check for NPM dependency updates

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
Command '('git', 'push', 'https://github.com/cockpituous/welder-web', '+HEADNone/heads/npm-update-@babel/polyfill-20190912-053232')' returned non-zero exit status 1.: https://209.132.184.41:8493/logs/npm-update-780-20190912-053131/

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "@babel/polyfill": "7.6.0",
webpack.config.js:  // redux-saga uses generators, babel compiles using regenerator runtime included in @babel/polyfill
webpack.config.js:  entry: ["@babel/polyfill", "./main.js"],
```

**Comment by marusak** [comment]
This version is obsoleted (see [here](https://babeljs.io/blog/2019/03/19/7.4.0#migration-from-core-js-2)). Is it really used or it can be dropped?

**Comment by martinpitt** [comment]
@marusak : It can be dropped, it doesn't get imported anywhere.

**Comment by martinpitt** [comment]
@henrywang: That's of no use, cockpituous would immediately create a new one. We need a PR first that drops this NPM dependency completely.

**Comment by henrywang** [comment]
@martinpitt, PR #787 got merged, can we close this PR? Thanks!

**Comment by martinpitt** [comment]
Indeed!

**Pull request closed without merging**
