### PR TITLE
tasks: Drop issue-scan

### PR DESCRIPTION
**Pull request by martinpitt**
This is now done by webhooks and AMQP.

### CODE REVIEW

**Comment by martinpitt** [comment]
This should stop the current stampede on bots issues like in #720

**Comment by martinpitt** [comment]
Setting to blocked for now until we sort this out for the other two projects. See https://github.com/cockpit-project/cockpit-podman/pull/142

**Comment by Gundersanne** [comment]
This can now be unblocked, as this is working.

A successful npm update run via amqp: cockpit-project/cockpit-podman#187.

**Comment by martinpitt** [comment]
@henrywang, can you please approve this in Lars'es stead, while he is on vac?

**Pull request merged**
