### PR TITLE
Dummy PR to test CI test scenario on branch rhel-8

### PR DESCRIPTION
**Pull request by henrywang**

### CODE REVIEW

**Comment by henrywang** [comment]
@martinpitt, [PR #541](https://github.com/cockpit-project/bots/pull/541) works. I'll close this PR after all tests got finished.

**Comment by martinpitt** [comment]
I wonder how this even works -- the target branch already has that commit, after all? https://github.com/weldr/cockpit-composer/commit/334e2239d4cba

**Comment by martinpitt** [comment]
Seems to fail on the same issue as master.

**Comment by henrywang** [comment]
@martinpitt, failed case comes from sources.test.js, which is the same as the other PR's.

**Comment by henrywang** [comment]
@martinpitt, the Travis fail is due to master merge conflict.

**Pull request closed without merging**
