### PR TITLE
Update translations from Fedora Zanata

### PR DESCRIPTION
**Pull request by cockpituous**
Update translations from Fedora Zanata
 * [x] po-refresh

### CODE REVIEW

**Comment by cockpituous** [comment]
po-refresh in progress on centosci-tasks-6clsl.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/po-refresh-766-20190823-035656/

**Comment by henrywang** [comment]
@martinpitt, is bot folder in cockpit-composer? Any changes on our CI? Thanks!

**Comment by marusak** [comment]
@henrywang no, there is something wrong with this, I'll take a look

**Comment by marusak** [comment]
So there was bug in our tests, fixed in https://github.com/cockpit-project/cockpit/pull/12652
I'll close this and let bots do it again, this time hopefully correctly :)

**Pull request closed without merging**
