### PR TITLE
Switch to osbuild-composer backend

### PR DESCRIPTION
**Pull request by larskarlitski**
osbuild-composer is a drop-in replacement for lorax-composer, providing
the same API:

    https://github.com/osbuild/osbuild-composer

Switch the dependency, documentation, and the name of the service for
the "Start Service" page.

### CODE REVIEW

**Comment by henrywang** [comment]
@larskarlitski, looks I can't push to your branch. I made an update about startService. Two services should get started for now, so I use cockpit.script to start them.
```diff
diff --git a/components/EmptyState/EmptyStateInactive.js b/components/EmptyState/EmptyStateInactive.js
index 94396979..f735b8d5 100644
--- a/components/EmptyState/EmptyStateInactive.js
+++ b/components/EmptyState/EmptyStateInactive.js
@@ -57,14 +57,14 @@ class EmptyStateInactive extends React.Component {
 
   startService(e) {
     if (!e || e.button !== 0) return;
-    let argv;
+    let script;
     if (this.state.enableService) {
-      argv = ["systemctl", "enable", "--now", "osbuild-composer.socket"];
+      script = "systemctl enable --now osbuild-composer.socket && systemctl enable --now osbuild-worker@1";
     } else {
-      argv = ["systemctl", "start", "osbuild-composer.socket"];
+      script = "systemctl start osbuild-composer.socket && systemctl start osbuild-worker@1";
     }
     cockpit
-      .spawn(argv, { superuser: "require", err: "message" })
+      .script(script, { superuser: "require", err: "message" })
       .then(() => this.props.fetchingBlueprints())
       .catch(err => {
         this.setState({ enableServiceFailure: err.message });
```

**Comment by henrywang** [comment]
@larskarlitski, and there's another two errors:
1. fetchBlueprintContentsSaga (fetching API `/api/v0/blueprints/depsolve/a`) does not work, and report `disconnected, Server has closed the connection.`
2. fetchInputsSaga (fetching API `/api/v0/modules/list/*`) does not work, and report `disconnected, Server has closed the connection.`

**Comment by henrywang** [comment]
@larskarlitski, I made some update anf fix for the test. Test works in my local env. But osbuild-worker got panic sometimes. Just attached the log in this comment.
[abc.log](https://github.com/weldr/cockpit-composer/files/3930625/abc.log)

**Comment by larskarlitski** [comment]
This is old and stale. Look at #868.

**Pull request closed without merging**
