### PR TITLE
package.json: Update @patternfly/react-icons package dependency

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
npm-update core-js done: https://github.com/cockpituous/welder-web/commits/npm-update-core-js-20191119-154747

**Comment by cockpituous** [comment]
Error accessing /repos/weldr/cockpit-composer/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value"None,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}: https://209.132.184.41:8493/logs/npm-update-828-20191119-154545/

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
components/ListView/BlueprintsDataList.js:import { PficonTemplateIcon } from "@patternfly/react-icons";
package.json:    "@patternfly/react-icons": "3.14.21",
```

**Comment by henrywang** [comment]
`@patternfly/react-icons` has been updated to `3.14.23` on PR #832. Close this PR.

**Pull request closed without merging**
