### PR TITLE
Allow user to fix depsolve errors on Edit page

### PR DESCRIPTION
**Pull request by jgiardino**
Before this update, if a blueprint had a package with a version that resulted in a depsolve failure, then an error message would display in the Edit page, and the only workaround for fixing the error is by editing the TOML file through the cli.

This update still displays the error message, but also includes the list of selected components so that the user can find the component that is mentioned in the error and resolve the issue by either removing the component or selecting a different version.

~Still to be included is the last statement in issue #718 (i.e. preventing the user from creating an image when an error exists).~ Going to defer this to a future PR.

Some ways to test this:
1. Add the package "soletta" to a blueprint. In this case, dependencies required by soletta are missing and will return an error. But the list of packages are still displayed. In this case, you will also see the Undo action display in the alert.
2. Edit the toml file of a blueprint to have bad version numbers for packages (or navigate to the Edit page for the atlas blueprint, which has old version numbers defined).

### CODE REVIEW

**Comment by jgiardino** [comment]
This is ready for review. After chatting with @larskarlitski, I'm going to create a separate PR to add the ability to block image creation when a depsolve failure occurs.

Please let me know if any updates are needed.
Thanks!

**Comment by jkozol** [comment]
This looks good to me. I have two things which I think are fine to add in separate PRs. 

1) I think we should display a similar error on the packages tab of the blueprint details page. Maybe it could direct the user to navigate to the edit blueprint page to fix the issue.

2) When I drill down to view the details of a component some of the information is missing and there is console error: `Error in fetchInputDeps TypeError: "response[responseIndex] is undefined"`

atlasDepError

**Comment by larskarlitski** [comment]
Rebased to include Jacob's eslint fixes and fix conflicts.

**Comment by henrywang** [comment]
@larskarlitski, feel free to merge it. All green now.

**Pull request merged**
