### PR TITLE
test: Update source repo URL to sway-copr because the fish repo URL does not work

### PR DESCRIPTION
**Pull request by henrywang**

### CODE REVIEW

**Comment by martinpitt** [comment]
Tests look good, but I wonder why this only ran the Fedora tests.. That's not what [testmap](https://github.com/cockpit-project/bots/blob/master/task/testmap.py) says..

**Comment by marusak** [comment]
> I wonder why this only ran the Fedora tests.. That's not what testmap says..

Interesting... It is possible to change base branch once PR is opened (`Edit` button next to the title) so I am wondering if the branch was not changed once PR was opened? If that is not the case, this needs some investigation

**Comment by martinpitt** [comment]
I didn't know that it was possible to adjust the branch target after opening.. @henrywang , is that what  happened?

**Comment by henrywang** [comment]
@martinpitt, but the test map works in PR #893. Interesting...

**Comment by martinpitt** [comment]
I rebased rhel-8 branch to release 12.1, so this is obsolete now.

**Pull request closed without merging**
