### PR TITLE
package.json: Update react-dom package dependency

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
main.js:import ReactDOM from "react-dom";
package.json:    "react-dom": "16.12.0",
```

**Comment by martinpitt** [comment]
[failure on edge](https://209.132.184.41:8493/logs/pull-837-20191202-212929-dbd202f1-weldr-cockpit-composer--fedora-31-edge/log.html), retrying

**Comment by martinpitt** [comment]
@henrywang : Edge test seems to fail rather often; the previous one was just the "unreachable hub", but the [current run](https://209.132.184.41:8493/logs/pull-837-20191202-212929-dbd202f1-weldr-cockpit-composer--fedora-31-edge/log.html) has some "real" failures. Is that known? Or does that point to some actual regression somewhere? (react-dom is not browser UI sensitive, it should fail everywhere or nowhere)

Retrying again.

**Comment by martinpitt** [comment]
Another error on [edge now](https://209.132.184.41:8493/logs/pull-837-20191203-095454-dbd202f1-weldr-cockpit-composer--fedora-31-edge/log.html), this time lorax-composer startup timed out (not browser related).

**Pull request merged**
