### PR TITLE
test: Add test case for manage sources page

### PR DESCRIPTION
**Pull request by henrywang**
1. Add data-* and id attributes to make search page element easy.
2. Add test case for manage sources page.

### CODE REVIEW

**Comment by henrywang** [comment]
The failed case on edge is due to issue #651

**Comment by martinpitt** [comment]
@henrywang : Would it be possible to skip this new test on Edge until this gets fixed properly? Then this feature is at least covered on the other two browsers, to avoid regressing there.

**Comment by henrywang** [comment]
@martinpitt, cloud you please do not merge this PR until the rhel-8-1 failed issue gets fixed. Thanks!

**Comment by henrywang** [comment]
@martinpitt, the add source in rhel-8-1 has been resolved. I think we can land this PR. Thanks.
The copy and paste test on edge still got failed, looks the Crtl-V does not work on edge sometimes.

**Comment by martinpitt** [comment]
@henrywang : I retried three times, edge just doesn't want to get green :-(

**Comment by henrywang** [comment]
@martinpitt, it's failed on copy and paste case. That's what I need #694 to debug copy and paste case.

**Pull request merged**
